services:
  nginx:
    # Eliminamos el mapeo de puertos que traía por defecto
    ports: !reset []
    networks:
      - default
      - proxy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bottrading.rule=Host(`bot.z2informatica.com`)"
      - "traefik.http.routers.bottrading.entrypoints=websecure"
      - "traefik.http.routers.bottrading.tls.certresolver=myresolver"
      - "traefik.http.services.bottrading.loadbalancer.server.port=80"
      - "traefik.http.routers.bottrading.middlewares=filtro-ip@file, limite-peticiones@file, cabeceras-seguras@file"
      - "traefik.docker.network=proxy-network"

networks:
  proxy-network:
    external: true
