# Generated by Django 5.2.17 on 2026-10-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationrun',
            name='trade_risk_pct',
            field=models.FloatField(default=5.0),
        ),
    ]
