# Generated by Django 5.2.17 on 2026-10-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0002_optimizationrun_trade_risk_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationresult',
            name='parameters',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
