# Generated by Django 5.2.17 on 2026-10-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0003_optimizationresult_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optimizationresult',
            name='strategy_name',
            field=models.CharField(max_length=255),
        ),
    ]
