# Generated by Django 5.2.17 on 2026-10-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0004_alter_optimizationresult_strategy_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationrun',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
