# Generated by Django 5.2.17 on 2026-10-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0005_optimizationrun_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationrun',
            name='selected_strategies',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
