# Generated by Django 5.2.17 on 2026-10-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0006_optimizationrun_selected_strategies'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationrun',
            name='selected_timeframes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
