# Generated by Django 6.1.1 on 2026-10-02 18:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('strategy_class', models.CharField(help_text='Ruta completa de la clase (ej: apps.strategies.ma_crossover.MACrossoverStrategy)', max_length=255, verbose_name='Clase Python')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Versión')),
                ('timeframe', models.CharField(choices=[('5m', '5 Minutos'), ('15m', '15 Minutos'), ('30m', '30 Minutos'), ('1h', '1 Hora'), ('4h', '4 Horas'), ('1d', '1 Día'), ('1w', '1 Semana')], default='1h', max_length=10, verbose_name='Timeframe')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Parámetros de configuración de la estrategia en JSON', verbose_name='Parámetros')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Estrategia',
                'verbose_name_plural': 'Estrategias',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
