# Generated by Django 6.1.1 on 2026-10-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, verbose_name='Símbolo')),
                ('timeframe', models.CharField(choices=[('5m', '5 Minutos'), ('15m', '15 Minutos'), ('30m', '30 Minutos'), ('1h', '1 Hora'), ('4h', '4 Horas'), ('1d', '1 Día'), ('1w', '1 Semana')], db_index=True, max_length=10, verbose_name='Timeframe')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Fecha y hora')),
                ('open', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Open')),
                ('high', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='High')),
                ('low', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Low')),
                ('close', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Close')),
                ('volume', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Volumen')),
            ],
            options={
                'verbose_name': 'Vela (Candle)',
                'verbose_name_plural': 'Velas (Candles)',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', 'timeframe', '-timestamp'], name='core_candle_symbol_cba8ad_idx')],
                'unique_together': {('symbol', 'timeframe', 'timestamp')},
            },
        ),
    ]
