# Generated by Django 6.1.1 on 2026-10-02 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE core_candle DROP CONSTRAINT core_candle_pkey;
            ALTER TABLE core_candle ADD PRIMARY KEY (id, timestamp);
            SELECT create_hypertable('core_candle', 'timestamp', if_not_exists => TRUE);
            """,
            reverse_sql="-- Reversing a hypertable back to a normal table is complex, typically we just drop it.",
        ),
    ]
