# Generated by Django 6.1.1 on 2026-10-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20261002_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Clave')),
                ('value', models.CharField(blank=True, max_length=500, verbose_name='Valor')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
    ]
