# Generated by Django 6.1.1 on 2026-10-02 18:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connectors', '0001_initial'),
        ('strategies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('symbol', models.CharField(max_length=20, verbose_name='Símbolo')),
                ('timeframe', models.CharField(choices=[('5m', '5 Minutos'), ('15m', '15 Minutos'), ('30m', '30 Minutos'), ('1h', '1 Hora'), ('4h', '4 Horas'), ('1d', '1 Día'), ('1w', '1 Semana')], max_length=10, verbose_name='Timeframe')),
                ('start_date', models.DateTimeField(verbose_name='Fecha inicio')),
                ('end_date', models.DateTimeField(verbose_name='Fecha fin')),
                ('initial_capital', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Capital inicial')),
                ('strategy_params', models.JSONField(default=dict, verbose_name='Parámetros de estrategia')),
                ('final_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Capital final')),
                ('total_return_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Retorno total (%)')),
                ('max_drawdown_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Drawdown máximo (%)')),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Ratio de Sharpe')),
                ('total_trades', models.IntegerField(default=0, verbose_name='Total operaciones')),
                ('winning_trades', models.IntegerField(default=0, verbose_name='Operaciones ganadoras')),
                ('losing_trades', models.IntegerField(default=0, verbose_name='Operaciones perdedoras')),
                ('profit_factor', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Profit Factor')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'Ejecutando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='Estado')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Mensaje de error')),
                ('results_data', models.JSONField(blank=True, default=dict, help_text='Resultados detallados: equity curve, trades, etc.', verbose_name='Datos detallados')),
                ('exchange_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backtest_runs', to='connectors.exchangeconnection', verbose_name='Conexión')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_runs', to='strategies.strategy', verbose_name='Estrategia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_runs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Ejecución de Backtest',
                'verbose_name_plural': 'Ejecuciones de Backtest',
                'ordering': ['-created_at'],
            },
        ),
    ]
