# Generated by Django 6.1.1 on 2026-10-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestrun',
            name='allow_pyramiding',
            field=models.BooleanField(default=False, help_text='Permite comprar de nuevo aunque ya haya una posición abierta', verbose_name='Permitir Pyramiding'),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='trade_risk_pct',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Porcentaje del capital libre a usar en cada compra', max_digits=5, verbose_name='Riesgo por operación (%)'),
        ),
    ]
