# Generated by Django 6.1.1 on 2026-10-02 18:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('name', models.CharField(help_text='Nombre identificador (ej: "Mi cuenta Binance")', max_length=100, verbose_name='Nombre')),
                ('exchange_id', models.CharField(help_text='Identificador del exchange (ej: binance, kraken, oanda)', max_length=50, verbose_name='Exchange ID')),
                ('market_type', models.CharField(choices=[('crypto', 'Criptomonedas'), ('forex', 'Divisas (Forex)'), ('stocks', 'Acciones'), ('etf', 'ETFs'), ('index', 'Índices'), ('futures', 'Futuros')], max_length=20, verbose_name='Tipo de mercado')),
                ('api_key', models.CharField(blank=True, default='', max_length=255, verbose_name='API Key')),
                ('api_secret', models.CharField(blank=True, default='', max_length=255, verbose_name='API Secret')),
                ('api_passphrase', models.CharField(blank=True, default='', help_text='Requerido por algunos exchanges (ej: Coinbase Pro)', max_length=255, verbose_name='Passphrase')),
                ('is_testnet', models.BooleanField(default=True, help_text='Usar entorno de pruebas del exchange', verbose_name='Usar Testnet')),
                ('extra_config', models.JSONField(blank=True, default=dict, help_text='Parámetros adicionales en formato JSON', verbose_name='Configuración extra')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_connections', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Conexión a Exchange',
                'verbose_name_plural': 'Conexiones a Exchanges',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
