# Generated by Django 6.1.1 on 2026-10-02 18:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connectors', '0001_initial'),
        ('strategies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('symbol', models.CharField(max_length=20, verbose_name='Símbolo')),
                ('timeframe', models.CharField(choices=[('5m', '5 Minutos'), ('15m', '15 Minutos'), ('30m', '30 Minutos'), ('1h', '1 Hora'), ('4h', '4 Horas'), ('1d', '1 Día'), ('1w', '1 Semana')], default='1h', max_length=10, verbose_name='Timeframe')),
                ('mode', models.CharField(choices=[('backtest', 'Backtesting'), ('paper', 'Paper Trading (Simulado)'), ('live', 'Trading en Vivo')], default='paper', max_length=20, verbose_name='Modo')),
                ('max_position_size', models.DecimalField(decimal_places=8, help_text='Cantidad máxima por operación', max_digits=20, verbose_name='Tamaño máximo de posición')),
                ('risk_per_trade_pct', models.DecimalField(decimal_places=2, default=2.0, help_text='Porcentaje del capital a arriesgar por operación', max_digits=5, verbose_name='Riesgo por operación (%)')),
                ('max_open_positions', models.IntegerField(default=3, verbose_name='Máximo posiciones abiertas')),
                ('daily_loss_limit_pct', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Límite pérdida diaria (%)')),
                ('status', models.CharField(choices=[('stopped', 'Detenido'), ('running', 'Ejecutando'), ('paused', 'Pausado'), ('error', 'Error')], default='stopped', max_length=20, verbose_name='Estado')),
                ('last_signal', models.JSONField(blank=True, null=True, verbose_name='Última señal')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Última ejecución')),
                ('exchange_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='connectors.exchangeconnection', verbose_name='Conexión al Exchange')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='strategies.strategy', verbose_name='Estrategia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Bot de Trading',
                'verbose_name_plural': 'Bots de Trading',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TradeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('symbol', models.CharField(max_length=20, verbose_name='Símbolo')),
                ('side', models.CharField(choices=[('buy', 'Compra'), ('sell', 'Venta')], max_length=10, verbose_name='Lado')),
                ('order_type', models.CharField(choices=[('market', 'Mercado'), ('limit', 'Límite'), ('stop', 'Stop'), ('stop_limit', 'Stop Limit'), ('trailing_stop', 'Trailing Stop')], max_length=20, verbose_name='Tipo')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Cantidad')),
                ('price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Precio')),
                ('cost', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Coste total')),
                ('fee', models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='Comisión')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('open', 'Abierta'), ('partially_filled', 'Parcialmente ejecutada'), ('filled', 'Ejecutada'), ('cancelled', 'Cancelada'), ('rejected', 'Rechazada'), ('expired', 'Expirada')], max_length=20, verbose_name='Estado')),
                ('exchange_order_id', models.CharField(blank=True, default='', max_length=255, verbose_name='ID orden exchange')),
                ('raw_response', models.JSONField(blank=True, default=dict, verbose_name='Respuesta raw')),
                ('pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='P&L')),
                ('signal_data', models.JSONField(blank=True, default=dict, help_text='Señal que generó esta operación', verbose_name='Datos de la señal')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='live_trading.tradingbot', verbose_name='Bot')),
            ],
            options={
                'verbose_name': 'Operación Real',
                'verbose_name_plural': 'Operaciones Reales',
                'ordering': ['-created_at'],
            },
        ),
    ]
