# Generated by Django 6.1.1 on 2026-10-04 11:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('level', models.CharField(choices=[('info', 'INFO'), ('warning', 'WARNING'), ('error', 'ERROR'), ('success', 'SUCCESS')], default='info', max_length=20, verbose_name='Nivel')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='live_trading.tradingbot', verbose_name='Bot')),
            ],
            options={
                'verbose_name': 'Log del Bot',
                'verbose_name_plural': 'Logs de Bots',
                'ordering': ['-created_at'],
            },
        ),
    ]
