# Generated by Django 6.1.1 on 2026-10-02 18:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('initial_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Balance inicial')),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Balance actual')),
                ('currency', models.CharField(default='USDT', max_length=10, verbose_name='Moneda base')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cuenta Paper',
                'verbose_name_plural': 'Cuentas Paper',
            },
        ),
        migrations.CreateModel(
            name='PaperTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('symbol', models.CharField(max_length=20, verbose_name='Símbolo')),
                ('side', models.CharField(choices=[('buy', 'Compra'), ('sell', 'Venta')], max_length=10, verbose_name='Lado')),
                ('order_type', models.CharField(choices=[('market', 'Mercado'), ('limit', 'Límite'), ('stop', 'Stop'), ('stop_limit', 'Stop Limit'), ('trailing_stop', 'Trailing Stop')], max_length=20, verbose_name='Tipo de orden')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Cantidad')),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Precio de entrada')),
                ('exit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Precio de salida')),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Stop Loss')),
                ('take_profit', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Take Profit')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('open', 'Abierta'), ('partially_filled', 'Parcialmente ejecutada'), ('filled', 'Ejecutada'), ('cancelled', 'Cancelada'), ('rejected', 'Rechazada'), ('expired', 'Expirada')], default='open', max_length=20, verbose_name='Estado')),
                ('pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='P&L')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Cerrada en')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='paper_trading.paperaccount', verbose_name='Cuenta')),
                ('strategy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_trades', to='strategies.strategy', verbose_name='Estrategia')),
            ],
            options={
                'verbose_name': 'Operación Paper',
                'verbose_name_plural': 'Operaciones Paper',
                'ordering': ['-created_at'],
            },
        ),
    ]
