# Generated by Django 6.1.1 on 2026-10-03 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_trading', '0001_initial'),
        ('paper_trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperaccount',
            name='bot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paper_account', to='live_trading.tradingbot', verbose_name='Bot Asociado'),
        ),
    ]
